name: Build
on:
  workflow_dispatch:
  push:
    branches: [ master,  github-workflow-playground ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    strategy:
      matrix:
        java: [8-jdk, 11-jdk, 15-jdk]
    runs-on: ubuntu-20.04
    container:
      image: openjdk:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v1
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build --stacktrace
      - name: Archive test results
        if: "${{ always() }}"
        uses: actions/upload-artifact@v2
        with:
          name: "test-results-${{ matrix.os }}"
          path: |
            build/reports/
            */build/reports/
